package cn.com.dhcc;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390- Generated source version: 2.0
 * 
 */
@WebService(name = "DWBHISServiceSoap", targetNamespace = "http://dhcc.com.cn")
public interface DWBHISServiceSoap {

	/**
	 * 
	 * @param xml
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "GetDepList", action = "http://dhcc.com.cn/NurDWB.Interface.Service.GetDepList")
	@WebResult(name = "GetDepListResult", targetNamespace = "http://dhcc.com.cn")
	@RequestWrapper(localName = "GetDepList", targetNamespace = "http://dhcc.com.cn", className = "cn.com.dhcc.GetDepList")
	@ResponseWrapper(localName = "GetDepListResponse", targetNamespace = "http://dhcc.com.cn", className = "cn.com.dhcc.GetDepListResponse")
	public String getDepList(@WebParam(name = "XML", targetNamespace = "http://dhcc.com.cn") String xml);

	/**
	 * 
	 * @param xml
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "GetOrderListByAdm", action = "http://dhcc.com.cn/NurDWB.Interface.Service.GetOrderListByAdm")
	@WebResult(name = "GetOrderListByAdmResult", targetNamespace = "http://dhcc.com.cn")
	@RequestWrapper(localName = "GetOrderListByAdm", targetNamespace = "http://dhcc.com.cn", className = "cn.com.dhcc.GetOrderListByAdm")
	@ResponseWrapper(localName = "GetOrderListByAdmResponse", targetNamespace = "http://dhcc.com.cn", className = "cn.com.dhcc.GetOrderListByAdmResponse")
	public String getOrderListByAdm(@WebParam(name = "XML", targetNamespace = "http://dhcc.com.cn") String xml);

	/**
	 * 
	 * @param xml
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "GetPatListByDep", action = "http://dhcc.com.cn/NurDWB.Interface.Service.GetPatListByDep")
	@WebResult(name = "GetPatListByDepResult", targetNamespace = "http://dhcc.com.cn")
	@RequestWrapper(localName = "GetPatListByDep", targetNamespace = "http://dhcc.com.cn", className = "cn.com.dhcc.GetPatListByDep")
	@ResponseWrapper(localName = "GetPatListByDepResponse", targetNamespace = "http://dhcc.com.cn", className = "cn.com.dhcc.GetPatListByDepResponse")
	public String getPatListByDep(@WebParam(name = "XML", targetNamespace = "http://dhcc.com.cn") String xml);

	/**
	 * 
	 * @param xml
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "GetUserListByDep", action = "http://dhcc.com.cn/NurDWB.Interface.Service.GetUserListByDep")
	@WebResult(name = "GetUserListByDepResult", targetNamespace = "http://dhcc.com.cn")
	@RequestWrapper(localName = "GetUserListByDep", targetNamespace = "http://dhcc.com.cn", className = "cn.com.dhcc.GetUserListByDep")
	@ResponseWrapper(localName = "GetUserListByDepResponse", targetNamespace = "http://dhcc.com.cn", className = "cn.com.dhcc.GetUserListByDepResponse")
	public String getUserListByDep(@WebParam(name = "XML", targetNamespace = "http://dhcc.com.cn") String xml);

	/**
	 * 
	 * @param xml
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "GetWardList", action = "http://dhcc.com.cn/NurDWB.Interface.Service.GetWardList")
	@WebResult(name = "GetWardListResult", targetNamespace = "http://dhcc.com.cn")
	@RequestWrapper(localName = "GetWardList", targetNamespace = "http://dhcc.com.cn", className = "cn.com.dhcc.GetWardList")
	@ResponseWrapper(localName = "GetWardListResponse", targetNamespace = "http://dhcc.com.cn", className = "cn.com.dhcc.GetWardListResponse")
	public String getWardList(@WebParam(name = "XML", targetNamespace = "http://dhcc.com.cn") String xml);

}
