
package com.sybercare.hospital.common.WebServiceClient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ServiceSoap", targetNamespace = "http://pda.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServiceSoap {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "HelloWorld", action = "http://pda.org/HelloWorld")
    @WebResult(name = "HelloWorldResult", targetNamespace = "http://pda.org/")
    @RequestWrapper(localName = "HelloWorld", targetNamespace = "http://pda.org/", className = "WebServiceClient.HelloWorld")
    @ResponseWrapper(localName = "HelloWorldResponse", targetNamespace = "http://pda.org/", className = "WebServiceClient.HelloWorldResponse")
    public String helloWorld();

    /**
     * 
     * @param xml
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetAllInpOrderSchedules", action = "http://pda.org/GetAllInpOrderSchedules")
    @WebResult(name = "GetAllInpOrderSchedulesResult", targetNamespace = "http://pda.org/")
    @RequestWrapper(localName = "GetAllInpOrderSchedules", targetNamespace = "http://pda.org/", className = "WebServiceClient.GetAllInpOrderSchedules")
    @ResponseWrapper(localName = "GetAllInpOrderSchedulesResponse", targetNamespace = "http://pda.org/", className = "WebServiceClient.GetAllInpOrderSchedulesResponse")
    public String getAllInpOrderSchedules(
            @WebParam(name = "xml", targetNamespace = "http://pda.org/")
                    String xml);

    /**
     * 
     * @param xml
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetAllMaxVitalSignsInfo", action = "http://pda.org/GetAllMaxVitalSignsInfo")
    @WebResult(name = "GetAllMaxVitalSignsInfoResult", targetNamespace = "http://pda.org/")
    @RequestWrapper(localName = "GetAllMaxVitalSignsInfo", targetNamespace = "http://pda.org/", className = "WebServiceClient.GetAllMaxVitalSignsInfo")
    @ResponseWrapper(localName = "GetAllMaxVitalSignsInfoResponse", targetNamespace = "http://pda.org/", className = "WebServiceClient.GetAllMaxVitalSignsInfoResponse")
    public String getAllMaxVitalSignsInfo(
            @WebParam(name = "xml", targetNamespace = "http://pda.org/")
                    String xml);

    /**
     * 
     * @param xml
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "InsertXY", action = "http://pda.org/InsertXY")
    @WebResult(name = "InsertXYResult", targetNamespace = "http://pda.org/")
    @RequestWrapper(localName = "InsertXY", targetNamespace = "http://pda.org/", className = "WebServiceClient.InsertXY")
    @ResponseWrapper(localName = "InsertXYResponse", targetNamespace = "http://pda.org/", className = "WebServiceClient.InsertXYResponse")
    public String insertXY(
            @WebParam(name = "xml", targetNamespace = "http://pda.org/")
                    String xml);

}
